PT-476 add cache to promoition evaluation
VirtoCommerce/vc-module-marketing pull request #137
Opened 2021-04-02 13:08 UTC by ksavosteev

https://virtocommerce.atlassian.net/browse/PT-475

2021-04-02 13:20 UTC, Vectorfield4 approved these changes

2021-04-02 13:20 UTC, Vectorfield4 commented on src/VirtoCommerce.MarketingModule.Core/Model/Promotions/PromotionEvaluationContext.cs
> +            return string.Join("|", GetCacheKeyComponents().Select(x => x ?? "null").Select(x => x is ICacheKey cacheKey ? cacheKey.GetCacheKey() : x.ToString()));
Do we really need so long key?

2021-04-02 13:21 UTC, Vectorfield4 commented
Resolve duplication, please.

2021-04-05 11:25 UTC, tatarincev commented on src/VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/BasePromotionPolicy.cs
> +        protected abstract Task<PromotionResult> EvaluatePromotionCachelessAsync(PromotionEvaluationContext promoContext);
EvaluatePromotionCachelessAsync -> EvaluatePromotionWithNoCache or EvaluatePromotionWithoutCache (but it is not exactly)

2021-04-05 13:00 UTC, tatarincev requested changes
Forgot to click on "Request changes". Ignore this comment please

2021-04-05 14:33 UTC, tatarincev approved these changes

2021-04-06 07:18 UTC, merged

2021-04-12 15:48 UTC, artem-dudarev commented
This PR introduces multiple issues with cache keys that were already fixed in the platform:
https://github.com/VirtoCommerce/vc-platform/pull/2129