PT-1822 add lock to marketing context PromoEntry write and evaluate
VirtoCommerce/vc-module-marketing pull request #152
Opened 2021-05-21 14:17 UTC by ksavosteev

https://virtocommerce.atlassian.net/browse/PT-1820

2021-05-21 15:34 UTC, Vectorfield4 approved these changes

2021-05-21 18:03 UTC, akak1977 requested changes

2021-05-21 18:03 UTC, akak1977 commented on src/VirtoCommerce.MarketingModule.Core/Model/Promotions/DynamicPromotion.cs
> +
Why not lock just promoContext instead of the surrogate object?

2021-05-21 18:09 UTC, akak1977 commented on src/VirtoCommerce.MarketingModule.Core/Model/Promotions/DynamicPromotion.cs
> +
Well... Next, I have no idea how to repair the bug with minimal changes, but this solution reduces concurrency. Pay your attention.

2021-05-24 14:26 UTC, akak1977 approved these changes

2021-05-24 14:55 UTC, merged