PT-174: Save button accessibility
VirtoCommerce/vc-module-marketing pull request #155
Opened 2021-05-28 16:00 UTC by ErickLipin

2021-05-31 08:53 UTC, Vectorfield4 requested changes
https://betterprogramming.pub/refactoring-guard-clauses-2ceeaa1a9da

2021-05-31 08:53 UTC, Vectorfield4 commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                if (!equals) {
Inverse it.

2021-05-31 08:53 UTC, Vectorfield4 commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                        blade.origEntity.dynamicProperties.length && blade.currentEntity.dynamicProperties.length) {
Inverse it.

2021-06-03 11:50 UTC, akak1977 approved these changes

2021-06-03 13:24 UTC, ksavosteev commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                for (var origEntityDynamicProperty of blade.origEntity.dynamicProperties) {
originalEntityDynamicProperty

2021-06-03 13:24 UTC, ksavosteev commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                if (equals) return !equals;
return false
move to a new line

2021-06-03 13:24 UTC, ksavosteev commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                    !blade.origEntity.dynamicProperties.length || !blade.currentEntity.dynamicProperties.length) return !equals;
return false
move to a new line

2021-06-03 13:24 UTC, ksavosteev commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                    let currEntityDynamicProperty = blade.currentEntity.dynamicProperties.find(x => x.name == origEntityDynamicProperty.name);
currentEntityDynamicProperty

2021-06-03 13:24 UTC, ksavosteev commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                        let origValues = origEntityDynamicProperty.values.map(x => x.value);
originalValues

2021-06-03 13:24 UTC, ksavosteev commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                        let currValues = currEntityDynamicProperty.values.map(x => x.value);
currentValues

2021-06-03 13:24 UTC, ksavosteev commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                        // !!AND EMPTY ARRAYS!!
remove or make the comment more clear

2021-06-03 13:24 UTC, ksavosteev commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                return !equals;
add an empty line above

2021-06-03 22:52 UTC, Vectorfield4 requested changes

2021-06-03 22:52 UTC, Vectorfield4 commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                if (equals) return !equals;
```suggestion
                if (equals)
                     return false;
                     
```

2021-06-03 22:52 UTC, Vectorfield4 commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                    !blade.origEntity.dynamicProperties.length || !blade.currentEntity.dynamicProperties.length) return !equals;
```suggestion
                if ( !blade.origEntity.dynamicProperties ||
                     !blade.currentEntity.dynamicProperties ||
                     !blade.origEntity.dynamicProperties.length ||
                     !blade.currentEntity.dynamicProperties.length ) 
                return !equals;
                
```

2021-06-08 15:50 UTC, ksavosteev approved these changes

2021-06-08 18:30 UTC, Vectorfield4 approved these changes

2021-06-08 18:30 UTC, merged