PT-1830: Button SAVE still inactive after change Dynamic property
VirtoCommerce/vc-module-marketing pull request #156
Opened 2021-06-03 06:22 UTC by krankenbro

https://virtocommerce.atlassian.net/browse/PT-1828

2021-06-03 06:44 UTC, eMazeika requested changes

2021-06-03 06:44 UTC, eMazeika commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +            _.forEach(right, (rightProp, index) => {
refactor to use _.some() without the need of breaking the loop

2021-06-03 06:44 UTC, eMazeika commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
> +                if (!isEqual) isEqual = isValueIdEqual(leftProperty.values[0], rightProp.values[0]);
what about multi-value?

2021-06-03 06:44 UTC, eMazeika commented on src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
>                  if (blade.origEntity.dynamicProperties && blade.currentEntity.dynamicProperties &&
move result checking into if: if(result && ...)

2021-06-04 08:18 UTC, Vectorfield4 approved these changes

2021-06-17 16:35 UTC, closed without merging